### PR TITLE
Optimise metadatas encoding

### PR DESCRIPTION
**Pull request by ozmat**
Replace Lists and nub with Sets in the metadata encoding part (Layer -> toProtobuf)

### CODE REVIEW

**Comment by fosskers** [comment]
Thanks! This inspired me to do a whole load of performance improvements. I did use `Set` as you suggest here too, so that PR supersedes this one.

**Comment by ozmat** [comment]
That's great ! Thanks for all the performance improvements ;)

**Comment by fosskers** [comment]
I suppose you're actually using this library? Can I ask what you're using it for (I'm genuinely curious)?

**Comment by ozmat** [comment]
Exactly. We are using it to turn Geometries/GeoJSON into VectorTiles in order to serve tiles with a Haskell web server/PostGIS database.

**Comment by fosskers** [comment]
Nice! That's fantastic. Let me know if you have any more issues.

**Pull request closed without merging**
